### ISSUE TITLE
Readme broken link

### ISSUE THREAD

**Issue by 89z** [huntlabs/hunt-openssl#1]
The Readme has a link like this:

~~~
http://https://github.com/D-Programming-Deimos/openssl
~~~

should be:

~~~
https://github.com/D-Programming-Deimos/openssl
~~~

**Comment by Heromyth** [comment]
Thanks. It's fixed in commit https://github.com/huntlabs/hunt-openssl/commit/b8536685cad843a1fe81a9abf288f38ab0053f9b.
